### ISSUE TITLE
Compactors continue trying to run when full

### ISSUE THREAD

**Issue by crimsonblod** [CivClassic/FactoryMod#10]
Compactors continue trying to decompact items when the attached chest is full. According to a few people, when this issue was present in 1.12.2, sometimes it would consume compacted blocks, and delete the resulting stack of items, sometimes it would not, and it would be purely a visual/text spam issue.

In this instance, it was purely visual and text spam, and it was not consuming the three compacted stone remaining in the compactor on the top left of the factory's inventory.

Expected behavior would be shutting down when the attached inventory was completely full.

![IcxxUKL](https://user-images.githubusercontent.com/28963633/81358955-8262ce00-909d-11ea-8f8f-ce8083ca7f34.png)

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/FactoryMod/pull/13
