### ISSUE TITLE
Trapped chests don't make factories

### ISSUE THREAD

**Issue by Xavter** [CivClassic/FactoryMod#12]
When making factories, if you use a trapped chest for the chest component, the factory won't build. QoL issue that seems like an easy fix - assigned to D4, feel free to move.

**Comment by Maxopoly** [comment]
Would need extensive testing as there are a lot of ways to break stuff with this change by not doing it properly

**Comment by Maxopoly** [comment]
Is there any actual reason though why you should be able to make factories from trapped chests? 1.14 let's you place chests of the same type adjacent to each other, so seems kinda pointless.

**Comment by crimsonblod** [comment]
Could the reason it's like this in the first place be related to the redstone signal that trapped chests put out?

**Comment by Maxopoly** [comment]
No, it's just easier with only a chest and there was never a strong reason for allowing trapped chests, even less so no.

**Comment by Xavter** [comment]
>Is there any actual reason though why you should be able to make factories from trapped chests? 1.14 let's you place chests of the same type adjacent to each other, so seems kinda pointless.

Player confusion. People place trapped chests instead of chests when making factories, I've seen it happen a couple times at this point, one earlier today. I see no hard technical limitation to disallow trapped chest only factories, but it's good to know that it has land mines. Will label d3 tonight unless you state otherwise.

**Comment by Maxopoly** [comment]
Implemented by https://github.com/CivClassic/FactoryMod/pull/24
