### ISSUE TITLE
Update recipe textual representations

### ISSUE THREAD

**Issue by squareblob** [CivClassic/FactoryMod#36]
Understanding what a recipe does should not require an external resource. However, `getTextualOutputRepresentation` and `getTextualInputRepresentation` are often incomplete (sometimes nonexistent) or flawed. 

e.g. `RandomOutputRecipe` displays its textual output as "A random item". The description would be more useful if it also listed (for example) the top three most likely outputs followed by "and X other items". 

e.g. `PrintNoteRecipe`'s don't have descriptions

e.g. It's not clear from the description how exactly `WordBankRecipe` works

**Comment by Maxopoly** [comment]
Mostly because those two methods are meant for and used as a short bullet point like description, not really a full explaination
